### ISSUE TITLE
编译时出错了，请修复问题！！！

### ISSUE THREAD

**Issue by smtp268** [F-T-Otaku/Actions-ImmortalWrt-R1S_H5#1]
make[5]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shairport-sync-openssl/shairport-sync-3.3.8'
player.c:(.text+0x1c90): undefined reference to `apple_alac_init'
Makefile:522: recipe for target 'all' failed
collect2: error: ld returned 1 exit status
make[4]: Leaving directory '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shairport-sync-openssl/shairport-sync-3.3.8'
make[6]: *** [shairport-sync] Error 1
Makefile:122: recipe for target '/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shairport-sync-openssl/shairport-sync-3.3.8/.built' failed
make[5]: *** [all-recursive] Error 1
make[3]: Leaving directory '/workdir/openwrt/feeds/packages/sound/shairport-sync'
make[4]: *** [all] Error 2
time: package/feeds/packages/shairport-sync/openssl/compile#0.26#0.08#0.33
make[3]: *** [/workdir/openwrt/build_dir/target-aarch64_cortex-a53_musl/shairport-sync-openssl/shairport-sync-3.3.8/.built] Error 2
    ERROR: package/feeds/packages/shairport-sync failed to build (build variant: openssl).
make[2]: *** [package/feeds/packages/shairport-sync/compile] Error 1
package/Makefile:114: recipe for target 'package/feeds/packages/shairport-sync/compile' failed
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
package/Makefile:110: recipe for target '/workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
make: *** [world] Error 2
Error: Process completed with exit code 2.

**Comment by F-T-Otaku** [comment]
已解决，确认是airplay2的一个依赖的bug，自行制作.config文件的时候不点airplay2就行，或者直接复制我现在项目里的k54.config文件。

**Comment by F-T-Otaku** [comment]
已通过编译验证
