### ISSUE TITLE
您好，很喜欢您的这个项目，不知道最近怎么云编译一直失败

### ISSUE THREAD

**Issue by zyuseoi** [F-T-Otaku/Actions-ImmortalWrt-R1S_H5#3]
每次都是在compile the firmware，错误代码如下：
make[2]: *** [package/Makefile:116: package/feeds/packages/curl/compile] Error 1
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [package/Makefile:110: /workdir/openwrt/staging_dir/target-aarch64_cortex-a53_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/workdir/openwrt'
make: *** [/workdir/openwrt/include/toplevel.mk:230: world] Error 2
Error: Process completed with exit code 2.

**Comment by F-T-Otaku** [comment]
Hi. 经过更新后，目前项目已经可以正常完成云编译. 
其实就是seed过时了，可以自己本地生成一份新的seed扔到项目就行

**Comment by zyuseoi** [comment]
> Hi. 经过更新后，目前项目已经可以正常完成云编译. 其实就是seed过时了，可以自己本地生成一份新的seed扔到项目就行

感谢更新，您的项目对我这个小白很友好，很好用
